// Mutable workflow state for an auto claim entity.
// Tracks lifecycle status, coverage, assessment, approval, and payment.
package com.ziggy.insurance.domains.claim.auto;

import com.ziggy.insurance.domains.claim.models.ClaimStatus;

public class AutoClaimState {

    // ── Identity ──────────────────────────────────────────────────
    private String claimId;           // e.g. clm-a1b2c3d4 (generated by the service)
    private String policyId;          // links back to policy/auto/{policyId}
    private String policyHolderId;

    // ── Status ────────────────────────────────────────────────────
    private ClaimStatus status;
    private String rejectionReason;   // set only when coverage is denied

    // ── Incident Details ──────────────────────────────────────────
    private String incidentDescription;
    private long incidentDate;
    private String incidentLocation;

    // ── Vehicle ───────────────────────────────────────────────────
    private String vehicleVin;
    private String vehicleMake;
    private String vehicleModel;
    private int vehicleYear;

    // ── Coverage (populated by verifyCoverage) ────────────────────
    private String coverageType;      // COLLISION | COMPREHENSIVE
    private int deductible;

    // ── Assessment (populated by dispatchFieldAdjuster) ───────────
    private String assignedAdjusterId;
    private String damageAssessment;
    private int estimatedRepairCost;

    // ── Approval (populated by adjusterApproval Signal) ───────────
    private String approvedByAdjusterId;
    private int approvedPayoutAmount;
    private long approvedAt;

    // ── Payment (populated from the payment domain's Nexus result) ─────────────────────
    private String paymentReference;
    private long closedAt;

    public AutoClaimState() {}

    public static AutoClaimState fromInput(AutoClaimInput input) {
        AutoClaimState s = new AutoClaimState();
        s.claimId = input.claimId();
        s.policyId = input.policyId();
        s.policyHolderId = input.policyHolderId();
        s.status = ClaimStatus.SUBMITTED;
        s.incidentDescription = input.incidentDescription();
        s.incidentDate = input.incidentDate();
        s.incidentLocation = input.incidentLocation();
        s.vehicleVin = input.vehicleVin();
        s.vehicleMake = input.vehicleMake();
        s.vehicleModel = input.vehicleModel();
        s.vehicleYear = input.vehicleYear();
        return s;
    }

    public String getClaimId() { return claimId; }
    public void setClaimId(String claimId) { this.claimId = claimId; }

    public String getPolicyId() { return policyId; }
    public void setPolicyId(String policyId) { this.policyId = policyId; }

    public String getPolicyHolderId() { return policyHolderId; }
    public void setPolicyHolderId(String policyHolderId) { this.policyHolderId = policyHolderId; }

    public ClaimStatus getStatus() { return status; }
    public void setStatus(ClaimStatus status) { this.status = status; }

    public String getRejectionReason() { return rejectionReason; }
    public void setRejectionReason(String rejectionReason) { this.rejectionReason = rejectionReason; }

    public String getIncidentDescription() { return incidentDescription; }
    public void setIncidentDescription(String incidentDescription) { this.incidentDescription = incidentDescription; }

    public long getIncidentDate() { return incidentDate; }
    public void setIncidentDate(long incidentDate) { this.incidentDate = incidentDate; }

    public String getIncidentLocation() { return incidentLocation; }
    public void setIncidentLocation(String incidentLocation) { this.incidentLocation = incidentLocation; }

    public String getVehicleVin() { return vehicleVin; }
    public void setVehicleVin(String vehicleVin) { this.vehicleVin = vehicleVin; }

    public String getVehicleMake() { return vehicleMake; }
    public void setVehicleMake(String vehicleMake) { this.vehicleMake = vehicleMake; }

    public String getVehicleModel() { return vehicleModel; }
    public void setVehicleModel(String vehicleModel) { this.vehicleModel = vehicleModel; }

    public int getVehicleYear() { return vehicleYear; }
    public void setVehicleYear(int vehicleYear) { this.vehicleYear = vehicleYear; }

    public String getCoverageType() { return coverageType; }
    public void setCoverageType(String coverageType) { this.coverageType = coverageType; }

    public int getDeductible() { return deductible; }
    public void setDeductible(int deductible) { this.deductible = deductible; }

    public String getAssignedAdjusterId() { return assignedAdjusterId; }
    public void setAssignedAdjusterId(String assignedAdjusterId) { this.assignedAdjusterId = assignedAdjusterId; }

    public String getDamageAssessment() { return damageAssessment; }
    public void setDamageAssessment(String damageAssessment) { this.damageAssessment = damageAssessment; }

    public int getEstimatedRepairCost() { return estimatedRepairCost; }
    public void setEstimatedRepairCost(int estimatedRepairCost) { this.estimatedRepairCost = estimatedRepairCost; }

    public String getApprovedByAdjusterId() { return approvedByAdjusterId; }
    public void setApprovedByAdjusterId(String approvedByAdjusterId) { this.approvedByAdjusterId = approvedByAdjusterId; }

    public int getApprovedPayoutAmount() { return approvedPayoutAmount; }
    public void setApprovedPayoutAmount(int approvedPayoutAmount) { this.approvedPayoutAmount = approvedPayoutAmount; }

    public long getApprovedAt() { return approvedAt; }
    public void setApprovedAt(long approvedAt) { this.approvedAt = approvedAt; }

    public String getPaymentReference() { return paymentReference; }
    public void setPaymentReference(String paymentReference) { this.paymentReference = paymentReference; }

    public long getClosedAt() { return closedAt; }
    public void setClosedAt(long closedAt) { this.closedAt = closedAt; }
}
