// Input parameters for starting an AutoClaimWorkflow.
// The claim id is generated by the REST service before the Workflow starts.
package com.ziggy.insurance.domains.claim.auto;

public record AutoClaimInput(
    String claimId,
    String policyId,
    String policyHolderId,
    String incidentDescription,
    long incidentDate,
    String incidentLocation,
    String vehicleVin,
    String vehicleMake,
    String vehicleModel,
    int vehicleYear
) {}
