// Mutable workflow state for a property claim entity.
// Mirrors AutoClaimState, swapping vehicle fields for property fields and adding the
// CAT-event context (catEventId, damageTier) carried in from CATEventWorkflow.
package com.ziggy.insurance.domains.claim.property;

import com.ziggy.insurance.domains.claim.models.ClaimStatus;
import com.ziggy.insurance.domains.claim.models.DamageTier;

public class PropertyClaimState {

    private String claimId;           // e.g. clm-a1b2c3d4 (generated by the service)
    private String policyId;          // links back to policy/property/{policyId}
    private String policyHolderId;

    // ── CAT context (set only for CATEventWorkflow-spawned claims) ─
    private String catEventId;        // null for portal-filed claims
    private DamageTier damageTier;    // null for portal-filed claims

    private ClaimStatus status;
    private String rejectionReason;   // set only when the claim is denied

    private String incidentDescription;
    private long incidentDate;
    private String propertyAddress;
    private String propertyType;      // SINGLE_FAMILY | CONDO | RENTER

    // ── AI adjuster mode (observability for AI-vs-human dashboards) ─
    // One-way flag: once enabled (via the enableAiAdjuster signal or the intake flag) the
    // still-pending adjuster decisions route to the AI agents instead of waiting on a human.
    private boolean aiAdjusterEnabled;

    // ── Coverage (populated by verifyCoverage) ────────────────────
    private String coverageType;      // e.g. HO3 | HO6 | RENTERS
    private int deductible;

    // ── Assessment (populated by dispatchFieldAdjuster) ───────────
    private String assignedAdjusterId;
    private String damageAssessment;
    private int estimatedRepairCost;

    // ── Approval (populated by adjusterApproval Signal) ───────────
    private String approvedByAdjusterId;
    private int approvedPayoutAmount;
    private long approvedAt;

    // ── Payment (populated from the payment domain's Nexus result) ─────────────────────
    private String paymentReference;
    private long closedAt;

    public PropertyClaimState() {}

    public static PropertyClaimState fromInput(PropertyClaimInput input) {
        PropertyClaimState s = new PropertyClaimState();
        s.claimId = input.claimId();
        s.policyId = input.policyId();
        s.policyHolderId = input.policyHolderId();
        s.catEventId = input.catEventId();
        s.damageTier = input.damageTier();
        s.status = ClaimStatus.SUBMITTED;
        s.incidentDescription = input.incidentDescription();
        s.incidentDate = input.incidentDate();
        s.propertyAddress = input.propertyAddress();
        s.propertyType = input.propertyType();
        s.aiAdjusterEnabled = input.aiAdjusterEnabled();
        return s;
    }

    public String getClaimId() { return claimId; }
    public void setClaimId(String claimId) { this.claimId = claimId; }

    public String getPolicyId() { return policyId; }
    public void setPolicyId(String policyId) { this.policyId = policyId; }

    public String getPolicyHolderId() { return policyHolderId; }
    public void setPolicyHolderId(String policyHolderId) { this.policyHolderId = policyHolderId; }

    public String getCatEventId() { return catEventId; }
    public void setCatEventId(String catEventId) { this.catEventId = catEventId; }

    public DamageTier getDamageTier() { return damageTier; }
    public void setDamageTier(DamageTier damageTier) { this.damageTier = damageTier; }

    public ClaimStatus getStatus() { return status; }
    public void setStatus(ClaimStatus status) { this.status = status; }

    public String getRejectionReason() { return rejectionReason; }
    public void setRejectionReason(String rejectionReason) { this.rejectionReason = rejectionReason; }

    public String getIncidentDescription() { return incidentDescription; }
    public void setIncidentDescription(String incidentDescription) { this.incidentDescription = incidentDescription; }

    public long getIncidentDate() { return incidentDate; }
    public void setIncidentDate(long incidentDate) { this.incidentDate = incidentDate; }

    public String getPropertyAddress() { return propertyAddress; }
    public void setPropertyAddress(String propertyAddress) { this.propertyAddress = propertyAddress; }

    public String getPropertyType() { return propertyType; }
    public void setPropertyType(String propertyType) { this.propertyType = propertyType; }

    public boolean isAiAdjusterEnabled() { return aiAdjusterEnabled; }
    public void setAiAdjusterEnabled(boolean aiAdjusterEnabled) { this.aiAdjusterEnabled = aiAdjusterEnabled; }

    public String getCoverageType() { return coverageType; }
    public void setCoverageType(String coverageType) { this.coverageType = coverageType; }

    public int getDeductible() { return deductible; }
    public void setDeductible(int deductible) { this.deductible = deductible; }

    public String getAssignedAdjusterId() { return assignedAdjusterId; }
    public void setAssignedAdjusterId(String assignedAdjusterId) { this.assignedAdjusterId = assignedAdjusterId; }

    public String getDamageAssessment() { return damageAssessment; }
    public void setDamageAssessment(String damageAssessment) { this.damageAssessment = damageAssessment; }

    public int getEstimatedRepairCost() { return estimatedRepairCost; }
    public void setEstimatedRepairCost(int estimatedRepairCost) { this.estimatedRepairCost = estimatedRepairCost; }

    public String getApprovedByAdjusterId() { return approvedByAdjusterId; }
    public void setApprovedByAdjusterId(String approvedByAdjusterId) { this.approvedByAdjusterId = approvedByAdjusterId; }

    public int getApprovedPayoutAmount() { return approvedPayoutAmount; }
    public void setApprovedPayoutAmount(int approvedPayoutAmount) { this.approvedPayoutAmount = approvedPayoutAmount; }

    public long getApprovedAt() { return approvedAt; }
    public void setApprovedAt(long approvedAt) { this.approvedAt = approvedAt; }

    public String getPaymentReference() { return paymentReference; }
    public void setPaymentReference(String paymentReference) { this.paymentReference = paymentReference; }

    public long getClosedAt() { return closedAt; }
    public void setClosedAt(long closedAt) { this.closedAt = closedAt; }
}
