// Input parameters for starting a PropertyClaimWorkflow.
// The claim id is generated by the REST service (or by CATEventWorkflow) before the
// Workflow starts. catEventId and damageTier are null for portal-filed claims and are
// set only when the claim originates from a CATEventWorkflow fan-out.
package com.ziggy.insurance.domains.claim.property;

import com.ziggy.insurance.domains.claim.models.DamageTier;

public record PropertyClaimInput(
    String claimId,
    String policyId,
    String policyHolderId,
    String catEventId,
    DamageTier damageTier,
    String incidentDescription,
    long incidentDate,
    String propertyAddress,
    String propertyType,        // SINGLE_FAMILY | CONDO | RENTER
    // Opt a claim into AI adjustment at intake (fully-autonomous demo). Defaults to false via
    // the convenience constructor below; the enableAiAdjuster signal is the primary mechanism.
    boolean aiAdjusterEnabled
) {

    // Backward-compatible constructor: portal-filed and CAT-spawned claims open in the default
    // human-adjuster mode (aiAdjusterEnabled = false) and may be switched later via the signal.
    public PropertyClaimInput(
            String claimId,
            String policyId,
            String policyHolderId,
            String catEventId,
            DamageTier damageTier,
            String incidentDescription,
            long incidentDate,
            String propertyAddress,
            String propertyType) {
        this(claimId, policyId, policyHolderId, catEventId, damageTier,
            incidentDescription, incidentDate, propertyAddress, propertyType, false);
    }
}
