// Input parameters for starting a PropertyClaimWorkflow.
// The claim id is generated by the REST service (or by CATEventWorkflow) before the
// Workflow starts. catEventId and damageTier are null for portal-filed claims and are
// set only when the claim originates from a CATEventWorkflow fan-out.
package com.ziggy.insurance.domains.claim.property;

import com.ziggy.insurance.domains.claim.models.DamageTier;

public record PropertyClaimInput(
    String claimId,
    String policyId,
    String policyHolderId,
    String catEventId,
    DamageTier damageTier,
    String incidentDescription,
    long incidentDate,
    String propertyAddress,
    String propertyType        // SINGLE_FAMILY | CONDO | RENTER
) {}
